version: '3'
services:
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
  mongo_init:
    build: ./mongo_init
    links:
      - mongodb
  webserver:
    build: ./web_app
    command: python -u app.py
    ports:
      - 5000:5000
    volumes:
      - ./web_app:/app
      #- ./web_app:/app
      #- ./web_app:/usr/src/app
    links:
      - mongodb